apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hpa-test
  namespace: conexa
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "50%"
      maxUnavailable: "25%"

  # ✅ TESTE: deixe SEM replicas para ver o default do K8s (1),
  # e depois o HPA ajustando para minReplicas.
  replicas: 2

  selector:
    matchLabels:
      app: nginx-hpa-test

  template:
    metadata:
      labels:
        app: nginx-hpa-test
    spec:
      terminationGracePeriodSeconds: 10

      containers:
        - name: nginx
          image: nginx:1.25
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi

          # ✅ Health checks (sem Service/Ingress, kubelet acessa o pod direto)
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

      affinity:
        nodeAffinity:
          # ✅ Preferir SPOT (Karpenter)
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: karpenter.sh/capacity-type
                    operator: In
                    values: ["spot"]

          # ✅ TESTE: forçar arquitetura (descomente UMA opção)
          # requiredDuringSchedulingIgnoredDuringExecution:
          #   nodeSelectorTerms:
          #   - matchExpressions:
          #     - key: kubernetes.io/arch
          #       operator: In
          #       values: ["amd64"]

          # requiredDuringSchedulingIgnoredDuringExecution:
          #   nodeSelectorTerms:
          #   - matchExpressions:
          #     - key: kubernetes.io/arch
          #       operator: In
          #       values: ["arm64"]

        # ✅ Evitar colocar todos os pods no mesmo node (bom quando escalar)
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: nginx-hpa-test
                topologyKey: kubernetes.io/hostname

      # ✅ Espalhar por AZ
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: nginx-hpa-test

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa-test
  namespace: conexa
spec:
  minReplicas: 3
  maxReplicas: 6
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-hpa-test

  # ✅ CPU é o mais fácil pra testar (precisa metrics-server)
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30
